### ISSUE TITLE
Coach Team List needs to default to current Season

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-attendanceApp#35]
Observed by Yuri M. the Program Manager who is assigned to many teams over several years, as the PM. To repro:
1. Login as a coach with teams in prior seasons
2. Examine the list on the Teams page
Result:
The list includes many teams which would not be reporting or relevant to the coach's immediate needs.

Expected:
The list would default to the current, active teams

Exceptions:
- If out of season, such as July, then the most recent season would be acceptable as default
- The coach may want to "look back" for research purposes on prior rosters, attendance, etc. OR, start building out an upcoming roster. (In this event, a *Season Select option* would be appropriate. Feature ticket TBD)

**Comment by Ignacioals** [comment]
@CritiqalPete currently the app shows the teams list ordered by season in descending order, showing the teams from the latest season at the top, this is part of the API changes made on Jan 25
