### ISSUE TITLE
Students View not showing active enrollments

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-attendanceApp#52]
to observe:
1. Login as an active coach with a team and roster
2. Select a team
3. Choose Students from the bottom Nav
Result:
Two entries appear
Student A A 1
Student A A 2

Expected:
The list of students enrolled in Active teams seasons assigned to the coach, is displayed, grouped by Team Season

**Comment by Ignacioals** [comment]
@CritiqalPete students screen displays this two records only as this are hardcoded values, Students screen is still under development.

**Comment by CritiqalPete** [comment]
We should disable this option in the navigation menu in till the view is working
